baseURL: https://cyberjake.xyz
languageCode: en-us
title: Cyb3r Jak3
theme: "toha"

enableEmoji: true

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON


# Site parameters
params:
  # # GitHub repo URL of your site
  # gitRepo: https://github.com/hugo-toha/hugo-toha.github.io

  logo:
    favicon: /images/site/favicon.png

  darkMode:
    provider: darkreader
    enable: true
    default: system

  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    analytics:
      enabled: false

  comment:
    giscus:
      repo: Cyb3r-Jak3/portfolio
      repoID: R_kgDOILD6BQ
      category: Giscus
      categoryID: DIC_kwDOILD6Bc4CR_Xh
      theme: dark
      map: url
      reaction: 1
      metadata: 0
      inputPosition: bottom
      crossOrigin: anonymous
  showFlags: false
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    # template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: false
    newsletter:
      enable: false