baseURL: https://cyberjake.xyz
languageCode: en-us
title: Cyb3r Jak3

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts


enableEmoji: true

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON


# Site parameters
params:
  gitRepo: https://github.com/Cyb3r-Jak3/portfolio

  logo:
    favicon: /images/site/favicon.png

  features:
    darkMode:
      enable: true
    portfolio:
      enable: true
    analytics:
      enabled: false

  comment:
    enable: false
  #   giscus:
  #     repo: Cyb3r-Jak3/portfolio
  #     repoID: R_kgDOILD6BQ
  #     category: Giscus
  #     categoryID: DIC_kwDOILD6Bc4CR_Xh
  #     theme: dark
  #     map: url
  #     reaction: 1
  #     metadata: 0
  #     inputPosition: bottom
  #     crossOrigin: anonymous
  flags:
    enable: true

  footer:
    credentials:
      enable: false
    newsletter:
      enable: false

sitemap:
  changefreq: weekly
  filename: sitemap.xml
