name: Compress Images
on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Compress Images
        uses: calibreapp/image-actions@a9a4a930a4c5b58474b15a278333f9f07b8d3ee4 # main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}