name: Build & Check

on:
  push:
    paths:
      - archetyes/**
      - assets/**
      - content/**
      - data/**
      - layouts/**
      - static/**
      - config.yaml
      - .github/workflows/main.yml

jobs:
  Site:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: bash build.sh

      # - name: HTML5 Validation
      #   uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      #   with:
      #       root: public/
      #       format: json
      #       css: true
      #       log_level: INFO
            # extra: --ignore-re Attribute "built"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: site-artifacts
          path: |
            public/